movies/menu/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.main_menu, name="main_menu"),
               path("start_search/", views.start_search, name="start_search")]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from menu.views import page_not_found
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls")),
    path("movies_search/", include("movie.urls")),
    path("users/", include("users.urls")),
    path("playlist/", include("playlist.urls")),
    path("forum/", include("forum.urls")),
] + debug_toolbar_urls()
handler404 = page_not_found

movies/playlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",
         views.playlist_menu,
         name="playlist_menu"),

    path("create_playlist/",
         views.create_playlist,
         name="create_playlist"),

    path("view_playlists/",
         views.view_playlists,
         name="view_playlists"),

    path(
        "view_playlist/<int:playlist_id>/",
        views.view_single_playlist,
        name="view_single_playlist",
    ),
    path(
        "add_movie_to_playlist/<int:movie_id>/",
        views.add_movie_to_playlist,
        name="add_movie_to_playlist",
    ),
    path(
        "remove_movie_from_playlist/<int:playlist_id>/<int:movie_id>/",
        views.remove_movie_from_playlist,
        name="remove_movie_from_playlist",
    ),
    path(
        "delete_playlist/<int:playlist_id>/",
        views.delete_playlist,
        name="delete_playlist",
    ),
    path(
        "get_recommendation_for_all_playlists/",
        views.get_recommendation_for_all_playlists,
        name="get_recommendation_for_all_playlists",
    ),
    path(
        "get_recommendation_for_playlist/<int:playlist_id>/",
        views.get_recommendation_for_playlist,
        name="get_recommendation_for_playlist",
    ),
    path("playlist_lda_summary/<int:playlist_id>/",
         views.playlist_lda_summary,
         name="playlist_lda_summary"),

    path("get_user_playlist_topics/<int:playlist_id>/",
         views.get_user_playlist_topics,
         name="get_user_playlist_topics",),
]

movies/users/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [
    path("user_home/", views.user_home, name="user_home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register_user"),
    path("logout/", views.logout_user, name="logout"),
    path("change_password/", views.change_password, name="change_password"),
    path("view_friends/", views.user_view_friends, name="view_friends"),
    path("user_search/", views.user_search, name="user_search"),
    path("view_user_profile/<str:username>/", views.show_user, name="show_user"),
    path("add_friend/<int:friend_id>/", views.user_add_friends, name="user_add_friends")
]

movies/playlist/models.py
from django.db import models
from movie.models import Movie
from django.contrib.auth.models import User  # Import the User model
from django.urls import reverse


class Playlist(models.Model):
    name = models.CharField(max_length=100)
    movie = models.ManyToManyField(Movie, related_name="playlist")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="playlists")

    def get_absolute_url(self):
        return reverse("view_single_playlist", kwargs={"playlist_id": self.id})

    def __str__(self):
        return self.name

movies/playlist/forms.py
from django import forms
from .models import Playlist
from movie.models import Rating


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ["name"]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["rating"]
        widgets = {"rating": forms.NumberInput(attrs={"min": 1, "max": 5})}  # Assuming a rating scale of 1 to 5

movies/playlist/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db import IntegrityError

import playlist
from movie.models import Movie, MovieMetaData, Rating, UserTopicDistribution, TopicDescription, MovieGenres, \
    MovieLanguages
from .models import Playlist
from .forms import PlaylistForm, RatingForm

from django.conf import settings

from factorization_machine.recommendations import produce_recommendations
from factorization_machine.recommendations import get_combined_features

from django.db.models import Count

from  factorization_machine.precompute_recommendations import group_recommendation

from gensim.models import Word2Vec
from django.db import transaction

from django.core.paginator import Paginator

from django.core.cache import cache


# Create your views here.
# ADD: param to show movie in get_abs_url for movie to pass corresponding url to go back


@login_required
def playlist_menu(request):
    return render(request, "playlist/playlist_menu.html")


@login_required
def create_playlist(request):
    if request.method == "POST":
        play_list_name = request.POST.get("play_list_name")

        existing_playlist = Playlist.objects.filter(name=play_list_name, user=request.user).first()

        if existing_playlist:
            return render(
                request,
                "playlist/create_playlist.html",
                {"error_message": "A playlist with this name already exists."},
            )
        else:
            Playlist.objects.create(name=play_list_name, user=request.user)
            return HttpResponseRedirect(reverse("main_menu"))

    else:
        return render(request, "playlist/create_playlist.html")


@login_required
def view_playlists(request):

    playlists = Playlist.objects.filter(user=request.user)
    paginator = Paginator(playlists, 10)

    page_number = request.GET.get("page")

    page_obj = paginator.get_page(page_number)
    context = {"playlists": page_obj}

    return render(request, "playlist/view_all_playlists.html", context)


@login_required
def delete_playlist(request, playlist_id):
    playlist = get_object_or_404(Playlist, id=playlist_id)
    playlist.delete()

    return redirect("view_playlists")


@login_required
def remove_movie_from_playlist(request, playlist_id, movie_id):
    playlist = get_object_or_404(Playlist, id=playlist_id, user=request.user)
    movie = get_object_or_404(Movie, movie_id=movie_id)

    with transaction.atomic():
        playlist.movie.remove(movie)

        rating = Rating.objects.get(movie=movie, user=request.user)
        rating.delete()

    return redirect("view_single_playlist", playlist_id=playlist.id)


@login_required
def view_single_playlist(request, playlist_id: int):

    playlist = get_object_or_404(Playlist, id=playlist_id)
    movies = playlist.movie.all()

    if request.method == "POST" and "name" in request.POST:
        form = PlaylistForm(request.POST, instance=playlist)

        if form.is_valid():
            form.save()
            return redirect("view_single_playlist", playlist_id=playlist.id)
    else:
        form = PlaylistForm(instance=playlist)

    # Handle rating submission
    if request.method == "POST" and "rating" in request.POST:
        movie_id = request.POST.get("movie_id")
        movie = get_object_or_404(Movie, movie_id=movie_id)
        rating_form = RatingForm(request.POST)

        print(movie_id)

        if rating_form.is_valid():
            rating = rating_form.save(commit=False)
            rating.user = request.user
            rating.movie = movie

            print(rating)
            print(rating.rating)
            print(rating.user)
            print(rating.movie)

            existing_rating = Rating.objects.filter(user=request.user, movie=movie).first()

            print(existing_rating)

            if existing_rating:
                existing_rating.rating = rating.rating
                existing_rating.save()
            else:
                try:
                    rating.save()
                except IntegrityError:
                    pass

            return redirect("view_single_playlist", playlist_id=playlist.id)
    else:
        rating_form = RatingForm()

    movie_ratings_display = {movie.movie_id: (rating.rating if rating else None) for movie, rating in zip(movies, [Rating.objects.filter(user=request.user, movie=movie).first() for movie in movies])}

    print(movie_ratings_display)

    context = {
        "movies": movies,
        "playlist": playlist,
        "form": form,
        "rating_form": rating_form,
        "movie_ratings_display": movie_ratings_display,
    }

    return render(request, "playlist/view_single_playlist.html", context)




@login_required
def get_user_playlist_topics(request, playlist_id):


    user = request.user
    playlist = get_object_or_404(Playlist, id=playlist_id)

    try:

        user_playlist_dist = UserTopicDistribution.objects.get(user=user, playlist=playlist)
        distributions = user_playlist_dist.distribution

        print(distributions)

        distributions = [(index,distribution) for index,distribution in enumerate(distributions)]

        topic_descriptions = []

        distributions = sorted(distributions, key=lambda x : x[1], reverse=True)
        distributions = distributions[:10]

        for topic_idx,prob in distributions:

            topic_desc = TopicDescription.objects.get(topic_id=topic_idx)

            topic_descriptions.append(
                {
                'importance': prob,
                'name': "_".join(list(topic_desc.top_words)[:3]),
                'id': topic_idx
             }
            )

        return JsonResponse({"topics": topic_descriptions})  # Wrap in {"topics": ...}

    except UserTopicDistribution.DoesNotExist:
        return JsonResponse({"topics": []})


@login_required
def playlist_lda_summary(request, playlist_id):

    playlist = get_object_or_404(Playlist, id=playlist_id)
    movies = playlist.movie.all()

    movie_genres = MovieGenres.objects.filter(
        genres__in=movies
    ).annotate(
        movie_count=Count('genres')
    ).distinct()

    movie_languages = MovieLanguages.objects.filter(
        languages__in=movies
    ).annotate(
        movie_count=Count('languages')
    ).distinct()

    movie_genres = {genre.genre: genre.movie_count for genre in movie_genres}
    movie_languages = {language.language: language.movie_count for language in movie_languages}

    print(movie_genres)
    print(movie_languages)

    return render(request, "playlist/show_user_topics.html", context={"playlist_id": playlist_id,
                                                                                    "movie_languages":movie_languages,
                                                                                    "movie_genres":movie_genres
                                                                                    })




@login_required
def add_movie_to_playlist(request, movie_id):
    movie = get_object_or_404(Movie, movie_id=movie_id)

    if request.method == "POST":
        play_list_name = request.POST.get("play_list_name")
        playlists = Playlist.objects.filter(user=request.user)

        try:
            playlist = playlists.get(name=play_list_name)
        except Playlist.DoesNotExist:
            error_message = f"The playlist '{play_list_name}' does not exist."
            return render(
                request,
                "playlist/add_movie_to_playlist.html",
                {
                    "movie_id": movie_id,
                    "playlists": playlists,
                    "movie": movie,
                    "error_message": error_message,
                },
            )

        if movie in playlist.movie.all():
            error_message = f"The movie '{movie.original_title}' is already in the playlist '{playlist.name}'."
            playlists = Playlist.objects.filter(user=request.user)

            return render(
                request,
                "playlist/add_movie_to_playlist.html",
                {
                    "movie_id": movie_id,
                    "playlists": playlists,
                    "movie": movie,
                    "error_message": error_message,
                },
            )

        playlist.movie.add(movie)
        return redirect("view_single_playlist", playlist_id=playlist.id)

    playlists = Playlist.objects.filter(user=request.user)

    if not playlists.exists():
        return redirect("create_playlist")

    return render(
        request,
        "playlist/add_movie_to_playlist.html",
        {"movie_id": movie_id, "playlists": playlists, "movie": movie},
    )



@login_required
def get_recommendation_for_playlist(request, playlist_id):

    """
    get recommendations for a user for based on all exact playlist
    """

    cache_key = f"{request.user.id}_{playlist_id}_playlist_recommendations"
    recommendations = cache.get(cache_key)

    if recommendations:

        movie_ids = json.loads(recommendations)
        recommendations = Movie.objects.filter(movie_id__in=movie_ids)

    else:

        wordvec = Word2Vec.load(str(settings.MODEL_DIR))
        playlist = Playlist.objects.get(id=playlist_id)

        selected_movies = set(playlist.movie.all())

        if not selected_movies:
            return render(
                request,
                "playlist/show_recommendations.html",
                {"error_message": "You do not have any movies in your playlists"},
            )

        recommendations = group_recommendation(selected_movies=selected_movies, wordvec=wordvec, user=request.user)

        movie_ids = [movie.movie_id for movie in recommendations]
        cache.set(cache_key, json.dumps(movie_ids), timeout=300)

movies/playlist/templates/playlist/add_movie_to_playlist.html
{% extends 'base.html' %}

{% block title %}Add {{movie.original_title}} to Playlist{% endblock %}

{% block header %}Add {{movie.original_title}} to Playlist{% endblock %}

{% block content %}

    {% if playlists %}
        <section class="produce_recommendations">
            <h2>Your Playlists:</h2>
            <ul>
                {% for playlist in playlists %}
                    <li>
                        <span class="label">playlist name: {{ playlist.name }}</span>
                    </li>
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% empty %}
                    <li>No playlist found.</li>
                {% endfor %}
            </ul>

    {% endif %}

            {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    <form method="POST" action="{% url 'add_movie_to_playlist' movie_id %}">
        {% csrf_token %}
        <label for="query">Name of Playlist:</label>
        <input type="text" id="query" name="play_list_name" placeholder="Enter playlist name" required>
        <button type="submit">Add</button>
    </form>


        </section>

    <nav>
        <p><a href="{% url 'playlist_menu' %}" class="bold-link">Return to the playlist menu</a></p>
    </nav>
{% endblock %}

movies/playlist/templates/playlist/create_playlist.html
{% extends 'base.html' %}

{% block title %}Create Playlist{% endblock %}

{% block header %}Create Playlist{% endblock %}

{% block content %}

    <form method="POST" action="{% url 'create_playlist' %}">
        {% csrf_token %}
        <label for="query">Name of Playlist:</label>
        <input type="text" id="query" name="play_list_name" placeholder="Enter playlist name" required>
        <button type="submit">Create</button>
    </form>

    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    <nav>
        <p><a href="{% url 'playlist_menu' %}" class="bold-link">Return to the playlist menu</a></p>
    </nav>

{% endblock %}

movies/playlist/templates/playlist/playlist_menu.html
{% extends 'base.html' %}

{% block title %}Playlist Menu{% endblock %}

{% block header %}Welcome to the Playlist Page{% endblock %}

{% block content %}

    <div class="button-container">
        <form action="{% url 'view_playlists' %}" method="get">
            <button type="submit">View My Playlists</button>
        </form>
    </div>

    <div class="button-container">
        <form action="{% url 'create_playlist' %}" method="get">
            <button type="submit">Create playlist</button>
        </form>
    </div>

    <div class="button-container">
        <form action="{% url 'get_recommendation_for_all_playlists' %}" method="get">
            <button type="submit">View my Recommendations</button>
        </form>
    </div>

    <nav>
        <p><a href="{% url 'main_menu' %}" class="bold-link">Return to the main menu</a></p>
    </nav>

{% endblock %}

movies/playlist/templates/playlist/show_recommendations.html
{% extends 'base.html' %}

{% block title %}My recommendations{% endblock %}

{% block header %}My recommendations{% endblock %}

{% block content %}

    {% load static   %}

    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}

    {% if result %}
        <section class="result">
            <h2>Recommendation Results:</h2>
            <ul>
                {% for movie in result %}
                    <li>
                        <span class="label">Movie Title:</span>
                        <a href="{{ movie.get_absolute_url }}">{{ movie.original_title }}</a>
                    </li>
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% empty %}
                    <li>No produce_recommendations found.</li>
                {% endfor %}
            </ul>

            <div class="pagination">
                <span class="step-links">
                    {% if result.has_previous %}
                        <a href="?page=1">&laquo; First</a>
                        <a href="?page={{ result.previous_page_number }}">Previous</a>
                    {% endif %}

                    <span class="current-page">
                        Page {{ result.number }} of {{ result.paginator.num_pages }}
                    </span>

                    {% if result.has_next %}
                        <a href="?page={{ result.next_page_number }}">Next</a>
                        <a href="?page={{ result.paginator.num_pages }}">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>


        </section>
    {% endif %}

    <div id="loading" style="display: none; text-align: center; margin-top: 20px;">
        <p>Loading...</p>
    </div>


    <nav>
        <p><a href="{% url 'playlist_menu' %}" class="bold-link">Return to the playlist menu</a></p>
    </nav>

    <script src="{% static 'playlist/javascript/loader.js' %}"></script>


{% endblock %}

movies/playlist/templates/playlist/show_user_topics.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Topics Visualization</title>

    <style>

        .back-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #3B82F6;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            margin-bottom: 20px;
        }

        .back-button:hover {
            background-color: #2563EB;
        }

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .header {
            margin-bottom: 30px;
        }

        .header h1 {
            color: #333;
            margin: 0 0 10px 0;
        }

        .header p {
            color: #666;
            margin: 0;
        }

        .visualization-container {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-bottom: 30px;
        }

        #topic-container {
            width: 100%;
            height: 600px;
        }

        .info-box {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            margin-top: 20px;
        }

        .info-box h3 {
            margin: 0 0 10px 0;
            color: #333;
        }

        .info-box p {
            color: #666;
            line-height: 1.6;
            margin: 0;
        }

        .details-grid {
            display: grid;
            grid-template-columns: 1fr;
            gap: 20px;
            margin-top: 30px;
        }

        @media (min-width: 768px) {
            .details-grid {
                grid-template-columns: 1fr 1fr;
            }
        }

        .details-box {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .details-box h2 {
            margin: 0 0 15px 0;
            color: #333;
        }
        .stats-container {
    display: flex;
    flex-direction: column;
    gap: 10px;
        }

        .stat-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #eee;
        }

        .stat-item:last-child {
            border-bottom: none;
        }

        .stat-label {
            color: #333;
            font-weight: 500;
        }

        .stat-count {
            color: #666;
            font-weight: 400;
        }

        /* Adjust grid for 4 boxes */
        @media (min-width: 768px) {
            .details-grid {
                grid-template-columns: repeat(2, 1fr);
                gap: 20px;
            }
        }

        @media (min-width: 1200px) {
            .details-grid {
                grid-template-columns: repeat(2, 1fr);
            }
        }

    </style>

</head>

<body>
    <div class="container">
        <a href="{% url 'view_single_playlist' playlist_id %}" class="back-button">Back to Playlist</a>
        <div class="header">
            <h1>Your Movie Topics</h1>
            <p>Topics discovered in your movie playlist using LDA analysis</p>
        </div>

        <div class="visualization-container">

            <div id="topic-container" data-playlist-id="{{ playlist_id }}"></div>

            <div class="info-box">
                <h3>About This Visualization</h3>
                <p>
                    • Circle size indicates topic importance in your movie collection<br>
                    • Hover over circles to see more details<br>
                    • Topics are based on movie descriptions and metadata
                </p>
            </div>
        </div>

        <div class="details-grid">
            <!-- Existing boxes -->
            <div class="details-box">
                <h2>Top Movies per Topic</h2>
                <div id="topic-details">
                    <!-- Will be populated by JavaScript -->
                </div>
            </div>

            <div class="details-box">
                <h2>Topic Distribution</h2>
                <div id="topic-stats">
                    <!-- Will be populated by JavaScript -->
                </div>
            </div>

            <!-- New boxes for genres and languages -->
            <div class="details-box">
                <h2>Genre Distribution</h2>
                <div class="stats-container">
                    {% for genre, count in movie_genres.items %}
                    <div class="stat-item">
                        <span class="stat-label">{{ genre }}</span>
                        <span class="stat-count">{{ count }} movies</span>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="details-box">
                <h2>Language Distribution</h2>
                <div class="stats-container">
                    {% for language, count in movie_languages.items %}
                    <div class="stat-item">
                        <span class="stat-label">{{ language }}</span>
                        <span class="stat-count">{{ count }} movies</span>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

<script src="{% static 'playlist/javascript/topic-visualization.js' %}"></script>

</body>

</html>

movies/playlist/templates/playlist/view_all_playlists.html
{% extends 'base.html' %}

{% block title %} View all Playlists {% endblock %}

{% block header %}Playlists{% endblock %}

{% block content %}

    {% if playlists %}
        <h2>Playlist Results:</h2>
        <ul>
            {% for playlist in playlists %}
                <li style="display: flex; align-items: center;">
                    <span class="label">Playlist Title:</span>
                    <a href="{{ playlist.get_absolute_url }}">{{ playlist.name }}</a>

                <form method="POST" action="{% url 'delete_playlist' playlist.id %}" style="margin-left: auto;">
                            {% csrf_token %}
                            <button type="submit">Remove playlist</button>
                </form>
                </li>
                {% if not forloop.last %}
                <hr>
                {% endif %}
            {% empty %}
            {% endfor %}
        </ul>

        <div class="pagination">
            <span class="step-links">
                {% if playlists.has_previous %}
                    <a href="?page=1">&laquo; First</a>
                    <a href="?page={{ playlists.previous_page_number }}">Previous</a>
                {% endif %}

                <span class="current-page">
                    Page {{ playlists.number }} of {{ playlists.paginator.num_pages }}
                </span>

                {% if playlists.has_next %}
                    <a href="?page={{ playlists.next_page_number }}">Next</a>
                    <a href="?page={{ playlists.paginator.num_pages }}">Last &raquo;</a>
                {% endif %}
            </span>
        </div>




    {% else %}
        <p>You have no Playlists.</p>
    {% endif %}

    <nav>
        <p><a href="{% url 'playlist_menu' %}" class="bold-link">Return to the playlist menu</a></p>
    </nav>


{% endblock %}

movies/playlist/templates/playlist/view_single_playlist.html
{% extends 'base.html' %}

{% block title %} View Playlist {% endblock %}

{% block header %}Playlists{% endblock %}


{% block action_buttons %}

    <form action="{% url 'users:view_friends' %}" method="get" class="header-form">
        <button type="submit" class="header-button">View Friends</button>
    </form>

    <form action="{% url 'playlist_lda_summary' playlist.id %}" method="get" class="header-form" style="margin-top: 10px;">
        <button type="submit" class="header-button">Get Playlist Summary</button>
    </form>

{% endblock %}

{% block content %}

    {% load my_tags %}
    {% load static %}

    <h2>{{ playlist.name }}</h2>

    <form method="POST" action="" style="display: flex; align-items: center;">
        {% csrf_token %}
        <div style="display: flex; align-items: center;">
            <label for="id_name" style="margin-right: 10px;">Name:</label>
            {{ form.name }}
            <button type="submit" style="margin-left: 10px;">Change Name</button>
        </div>
    </form>

    {% if movies %}
        <h2>Movies in {{ playlist.name }}:</h2>
        <ul>
            {% for movie in movies %}
                <li style="display: flex; align-items: center; justify-content: space-between;">
                    <div>
                        <span class="label">Movie Title:</span>
                        <a href="{{ movie.get_absolute_url }}" style="margin-right: 10px;">{{ movie.original_title }}</a>
                        <span style="font-weight: bold;">
                            {% if movie.movie_id in movie_ratings_display %}
                               (Rating: {{ movie_ratings_display|get_dict_value:movie.movie_id }} )
                            {% else %}
                                (Not Rated)
                            {% endif %}
                        </span>
                    </div>
                    <div class="button-container" style="display: flex; gap: 10px;">
                        <!-- Remove Movie from Playlist -->
                        <form method="POST" action="{% url 'remove_movie_from_playlist' playlist.id movie.movie_id %}">
                            {% csrf_token %}
                            <button type="submit">Remove from playlist</button>
                        </form>
                        <!-- Rate Movie -->
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="hidden" name="movie_id" value="{{ movie.movie_id }}">
                            {{ rating_form.rating }}
                            <button type="submit">Rate</button>
                        </form>
                    </div>
                </li>
                {% if not forloop.last %}
                <hr>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>No Movies found for {{ playlist.name }}.</p>
    {% endif %}


    <div id="loading" style="display: none; text-align: center; margin-top: 20px;">
        <p>Loading...</p>
    </div>


    <nav>
        <p><a href="{% url 'view_playlists' %}" class="bold-link loading-link">Return to your playlists</a></p>
    </nav>


    <nav>
        <p><a href="{% url 'get_recommendation_for_playlist' playlist.id %}" class="bold-link loading-link">View Recommendations for this playlist</a></p>
    </nav>

    <script src="{% static 'playlist/javascript/loader.js' %}"></script>

{% endblock %}