movies/menu/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.main_menu, name="main_menu"),
               path("start_search/", views.start_search, name="start_search")]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from menu.views import page_not_found
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls")),
    path("movies_search/", include("movie.urls")),
    path("users/", include("users.urls")),
    path("playlist/", include("playlist.urls")),
    path("forum/", include("forum.urls")),
] + debug_toolbar_urls()
handler404 = page_not_found

movies/users/urls.py
from django.urls import path
from . import views


app_name = "users"


urlpatterns = [
    path("user_home/", views.user_home, name="user_home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register_user"),
    path("logout/", views.logout_user, name="logout"),
    path("change_password/", views.change_password, name="change_password"),
    path("view_friends/", views.user_view_friends, name="view_friends"),
    path("user_search/", views.user_search, name="user_search"),
    path("view_user_profile/<str:username>/", views.show_user, name="show_user"),
    path("add_friend/<int:friend_id>/", views.user_add_friends, name="user_add_friends")
]

movies/users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class Friendship(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friends")
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend_of")

    class Meta:
        unique_together = ("user", "friend")  # Prevent duplicate friendships

    def __str__(self):
        return f"{self.user.username} is friends with {self.friend.username}"



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    def get_absolute_url(self):
        print("YES!")
        return reverse("users:show_user", kwargs={"username": self.user.username})

    def __str__(self):
        return self.user.username

movies/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


class LoginUserForm(forms.Form):
    username = forms.CharField(label="User Name", widget=forms.TextInput(attrs={"class": "form-input"}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-input"}))


class ChangePasswordForm(forms.Form):
    username = forms.CharField(label="User Name", widget=forms.TextInput(attrs={"class": "form-input"}))
    password = forms.CharField(label="Old Password", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    password2 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={"class": "form-input"}))


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label="User Name")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password",
            "password2",
        ]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords do not match!")
        return cd["password2"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exists!")
        return email

movies/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import JsonResponse
from django.shortcuts import render, reverse, get_object_or_404, redirect

from movie.models import UserTopicDistribution, TopicDescription
from .forms import LoginUserForm, RegisterUserForm, ChangePasswordForm
from .models import Friendship, Profile
from django.contrib import messages

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.db.models import Q

from populate_database.populate_user_profile import PopulateUserProfile



def create_user_info(request, username):

    context = {}

    user = User.objects.get(username=username)

    friends = Friendship.objects.filter(user=user)
    is_friend = friends.filter(friend=request.user).exists()

    context['user_name'] = username
    context['user_email'] = user.email
    context['user_date_joined'] = user.date_joined.strftime("%B %d, %Y")
    context['user_is_friend'] = is_friend
    context['user_id'] = user.id

    return context




def user_home(request):
    return render(request, "users/user_home.html")


@login_required
def user_add_friends(request, friend_id):

    user = request.user

    friend = get_object_or_404(User, id=friend_id)
    context = create_user_info(request, friend.username)


    if user == friend:
        context = {**context, **{"message": "You cannot add yourself as a friend.", "message_type": "error"}}

        return render(
            request,
            "users/show_friend.html",
            context = context,
        )

    if Friendship.objects.filter(user=user, friend=friend).exists() or Friendship.objects.filter(user=friend, friend=user).exists():

        context = {**context, **{"message": "You are already friends with this user.", "message_type": "error"}}

        return render(
            request,
            "users/show_friend.html",
            context = context,
        )

    Friendship.objects.create(user=user, friend=friend)
    Friendship.objects.create(user=friend, friend=user)

    context = {**context, **{"message":  f"You are now friends with {friend.username}!", "message_type": "success"}}

    return render(
        request,
        "users/show_friend.html",
        context = context,
    )


def show_user(request, username):

    context = create_user_info(request, username)
    return render(request, "users/show_friend.html", context=context)



@login_required
def user_view_friends(request):

    friend_ids = Friendship.objects.filter(user=request.user).values_list("friend", flat=True)
    friends = User.objects.filter(id__in=friend_ids)

    users_with_profiles = friends.select_related("profile")

    paginator = Paginator(users_with_profiles, 20)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {"friends": page_obj}
    return render(request, "users/friends.html", context=context)


def user_search(request):

    query = request.POST.get("query")
    users_with_profiles = {}

    if query:

        users = User.objects.filter(Q(username__icontains=query) |
                                    Q(email__icontains=query) |
                                    Q(first_name__icontains=query) |
                                    Q(last_name__icontains=query) |
                                    Q(first_name__icontains=query.split()[0],
                                    last_name__icontains=query.split()[-1]))[:10]

        users_with_profiles = users.select_related("profile")

        print(users_with_profiles)

    return render(request, "users/user_search.html", {"users": users_with_profiles})


def user_delete_friends(request):
    pass


def login_user(request):

    if request.method == "POST":
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user and user.is_active:
                login(request, user)
                messages.success(request, f"You are now logged in as {user.username}")
                return HttpResponseRedirect(reverse("main_menu"))
            else:
                messages.error(request, "Invalid username or password")
    else:
        form = LoginUserForm()

    return render(request, "users/login.html", {"form": form})


def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)

        if form.is_valid():
            # Create user but don't save to DB yet
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            # Save user to DB to get the ID
            user.save()

            # Now we have the user.id available
            user_profile = PopulateUserProfile(user_id=user.id)  # Pass user_id here
            user_profile.run()

            messages.success(
                request,
                f"Registration successful! You can now log in as {user.username}",
            )
            return render(request, "users/register_done.html")
    else:
        form = RegisterUserForm()

    return render(request, "users/register.html", {"form": form})


def create_user(request):
    return HttpResponse("create user")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("main_menu"))


def change_password(request):
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            old_password = form.cleaned_data["password"]
            new_password = form.cleaned_data["password2"]

            user = authenticate(request, username=username, password=old_password)
            if user:
                user.set_password(new_password)
                user.save()

                update_session_auth_hash(request, user)
                messages.success(request, "Your password has been successfully updated!")

                return HttpResponseRedirect(reverse("user_home"))

            else:
                return render(request, "users/change_password.html", {"error": "Wrong password or username", "form": form})
    else:
        form = ChangePasswordForm()

    return render(request, "users/change_password.html", {"form": form})

movies/users/templates/users/add_friend.html
{% extends 'base.html' %}

{% block title %}Friend Search{% endblock %}

{% block header %}
    <h1>Friend Search</h1>
{% endblock %}

{% block action_buttons %}
{% endblock %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

    <div class="search-container">
        <form method="POST" action="{% url 'users:add_friend' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="search-input-container">
                    <label for="query">Enter Friend Details:</label>
                    <input type="text" id="query" name="query" placeholder="Enter Friend Details">
                </div>
            </div>
            <button type="submit" class="search-btn">Search</button>
        </form>
    </div>

    {% if error %}
        <div class="error-message" style="color: red; margin-top: 20px;">
            <strong>Error:</strong> {{ error }}
        </div>
    {% endif %}

    {% if users %}
        <h2>Search Results:</h2>
        <ul>
            {% for user in users %}
                <li>
                    <span class="label">Friend Name: {{ user.username }} </span>
                </li>

                {% if not forloop.last %}
                <hr>
                {% endif %}
            {% empty %}
                <li>No users found.</li>
            {% endfor %}
        </ul>
    {% endif %}

    <nav>
        <p><a href="{% url 'users:user_home' %}" class="bold-link">Return to the user home page</a></p>
    </nav>

    <script src="{% static 'users/javascript/loader.js' %}"></script>
{% endblock %}

movies/users/templates/users/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>

    <main>
        <header>
            <h1>Change Password</h1>
        </header>

        {% if error %}
        <div class="error-message" style="color: red; margin-top: 20px;">
            <strong>Error:</strong> {{ error }}
        </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit">Submit</button></p>
        </form>

        <nav>
            <p><a href="{% url 'users:user_home' %}" class="bold-link">Return to the user home menu</a></p>
        </nav>

    </main>

</body>
</html>

movies/users/templates/users/friends.html
{% extends 'base.html' %}

{% block title %}My Friends{% endblock %}

{% block header %}
    {{ block.super }}
{% endblock %}

{% block action_buttons %}
    <form action="{% url 'users:user_search' %}" method="get">
        <button type="submit" style="padding: 5px 10px;">Look for a Friend</button>
    </form>
{% endblock %}

{% block content %}
    <ul>
        {% for friend in friends %}
            <li><a href="{{ friend.profile.get_absolute_url }}"> {{ friend.username }} </a></li>
        {% empty %}
            <li>You have no friends yet.</li>
        {% endfor %}
    </ul>

    <!-- Pagination Controls -->
    <div class="pagination">
        <span class="step-links">
            {% if friends.has_previous %}
                <a href="?page=1">&laquo; First</a>
                <a href="?page={{ friends.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current-page">
                Page {{ friends.number }} of {{ friends.paginator.num_pages }}
            </span>

            {% if friends.has_next %}
                <a href="?page={{ friends.next_page_number }}">Next</a>
                <a href="?page={{ friends.paginator.num_pages }}">Last &raquo;</a>
            {% endif %}
        </span>
    </div>

    <nav>
        <p><a href="{% url 'users:user_home' %}">Return to User Home</a></p>
    </nav>
{% endblock %}

movies/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>

    <main>

        <header>
            <h1>Log in</h1>
        </header>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
             <p>
                <a href="{% url 'users:change_password' %}" class="bold-link">Forgot your password?</a>
            </p>

            <p><button type="submit">Submit</button></p>
        </form>

        <nav>
             <p><a href="{% url 'users:user_home' %}" class="bold-link">Return to the user home</a></p>
        </nav>

    </main>

</body>

</html>

movies/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>

    <main>

        <header>
            <h1>Register</h1>
        </header>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit">Submit</button></p>
        </form>


            <nav>
                <p><a href="{% url 'users:user_home' %}" class="bold-link">Return to the user home</a></p>
            </nav>

    </main>

</body>
</html>

movies/users/templates/users/register_done.html
{% extends 'base.html' %}

{% block title %}Reviews{% endblock %}

{% block header %}Reviews{% endblock %}

{% block content %}

    <h1>Registration was successful!</h1>

    <nav>
        <p><a href="{% url 'main_menu' %}" class="bold-link">Return to the Main Menu</a></p>
    </nav>

{% endblock %}

movies/users/templates/users/show_friend.html
{% extends 'base.html' %}
{% block content %}
    <section class="display-details">
        <h2>{{ user_name }}</h2>
        <p><strong>Email:</strong> {{ user_email }}</p>
        <p><strong>Date Joined:</strong> {{ user_date_joined }}</p>
        <p><strong>Is Friend:</strong> {{ user_is_friend }}</p>
    </section>

    {% if message %}
        <div class="message {% if message_type == 'success' %}success-message{% else %}error-message{% endif %}">
            <p>{{ message }}</p>
        </div>
    {% endif %}

    <nav>
        <p><a href="{% url 'users:user_search' %}" class="bold-link">Return to the User Search</a></p>
    </nav>

    <nav>
        <p><a href="{% url 'users:view_friends' %}" class="bold-link">Return to Friends Page</a></p>
    </nav>

    <nav>
        <p><a href="{% url 'users:user_add_friends' user_id %}" class="bold-link">Add friend</a></p>
    </nav>



{% endblock %}

movies/users/templates/users/show_user_topics.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Topics Visualization</title>

    <style>

        .back-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #3B82F6;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            margin-bottom: 20px;
        }

        .back-button:hover {
            background-color: #2563EB;
        }

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .header {
            margin-bottom: 30px;
        }

        .header h1 {
            color: #333;
            margin: 0 0 10px 0;
        }

        .header p {
            color: #666;
            margin: 0;
        }

        .visualization-container {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-bottom: 30px;
        }

        #topic-container {
            width: 100%;
            height: 600px;
        }

        .info-box {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            margin-top: 20px;
        }

        .info-box h3 {
            margin: 0 0 10px 0;
            color: #333;
        }

        .info-box p {
            color: #666;
            line-height: 1.6;
            margin: 0;
        }

        .details-grid {
            display: grid;
            grid-template-columns: 1fr;
            gap: 20px;
            margin-top: 30px;
        }

        @media (min-width: 768px) {
            .details-grid {
                grid-template-columns: 1fr 1fr;
            }
        }

        .details-box {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .details-box h2 {
            margin: 0 0 15px 0;
            color: #333;
        }
    </style>

</head>

<body>
    <div class="container">
        <a href="{% url 'users:user_home' %}" class="back-button">Back to User Home</a>
        <div class="header">
            <h1>Your Movie Topics</h1>
            <p>Topics discovered in your movie playlist using LDA analysis</p>
        </div>

        <div class="visualization-container">
            <div id="topic-container"></div>

            <div class="info-box">
                <h3>About This Visualization</h3>
                <p>
                    • Circle size indicates topic importance in your movie collection<br>
                    • Hover over circles to see more details<br>
                    • Topics are based on movie descriptions and metadata
                </p>
            </div>
        </div>

        <div class="details-grid">
            <div class="details-box">
                <h2>Top Movies per Topic</h2>
                <div id="topic-details">
                    <!-- Will be populated by JavaScript -->
                </div>
            </div>

            <div class="details-box">
                <h2>Topic Distribution</h2>
                <div id="topic-stats">
                    <!-- Will be populated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

<script src="{% static 'users/javascript/topic-visualization.js' %}"></script>

</body>

</html>

movies/users/templates/users/user_home.html
{% extends 'base.html' %}

{% block title %}User Home{% endblock %}

{% block header %}
    <h1>Welcome to User Home</h1>
{% endblock %}

{% block content %}
    <div class="button-container">
        <form action="{% url 'users:register_user' %}" method="get">
            <button type="submit">Register</button>
        </form>
    </div>

    <div class="button-container">
        <form action="{% url 'users:login' %}" method="get">
            <button type="submit">Log In</button>
        </form>
    </div>

    <div class="button-container">
        <form action="{% url 'users:logout' %}" method="get">
            <button type="submit">Log Out</button>
        </form>
    </div>

    <div class="button-container">
        <form action="{% url 'users:change_password' %}" method="get">
            <button type="submit">Change Password</button>
        </form>
    </div>

    <nav>
        <p><a href="{% url 'main_menu' %}" class="bold-link">Return to the menu page</a></p>
    </nav>
{% endblock %}

movies/users/templates/users/user_search.html
{% extends 'base.html' %}

{% block title %}Friend Search{% endblock %}

{% block header %}
    <h1>Friend Search</h1>
{% endblock %}

{% block action_buttons %}
{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

    <div class="search-container">
        <form method="POST" action="{% url 'users:user_search' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="search-input-container">
                    <label for="query">Enter Friend Details:</label>
                    <input type="text" id="query" name="query" placeholder="Enter Friend Details">
                </div>
            </div>
            <button type="submit" class="search-btn">Search</button>
        </form>
    </div>

    {% if error %}
        <div class="error-message" style="color: red; margin-top: 20px;">
            <strong>Error:</strong> {{ error }}
        </div>
    {% endif %}

    {% if users %}
        <h2>Search Results:</h2>
        <ul>
            {% for user in users %}
                <li>
                    <span
                            class="label">Friend Name:
                    </span>
                    <a href="{{ user.profile.get_absolute_url }}"> {{ user.username }} </a>
                </li>

                {% if not forloop.last %}
                <hr>
                {% endif %}
            {% empty %}
                <li>No users found.</li>
            {% endfor %}
        </ul>
    {% endif %}

    <nav>
        <p><a href="{% url 'users:view_friends' %}" class="bold-link">Return to the Friends page</a></p>
    </nav>

    <script src="{% static 'users/javascript/loader.js' %}"></script>
{% endblock %}